### ISSUE TITLE
Super-Administrator vs. Administrator vs. Editor

### ISSUE THREAD

**Issue by andrepoddubny** [IISHF/web2019#14]
Currently the website provides rights for the "Super-Administrator" and "Administrators", with the latter in fact being only editors. It would be great if a third category could be created that have the rights to add new subpages and add potentially new features. Else, only you yourself, Stefan, can do all the work. Ideally you will get help from the IISHF Communication and Marketing Officer or some third person, such as Oleksandr Govorun (if you would like that).

**Comment by sgehrig** [comment]
The current system is not a full-fledged content management system and never was designed to be such a system. You have to differentiate static data from the dynamic data that's being powered by the database.

Static data is for example:
- `/privacy` the privacy page
- `/cookie` the cookie policy page 
- `/imprint` the imprint page
- `/about-sport` the about sport page

These pages consist of static content that can only be changed by changing the relevant templates (e.g. https://github.com/IISHF/web2019/blob/master/templates/about_sport/index.html.twig for the `/about-sport` page).

Another part of static data are the images used on the static pages and as part of the overall design. It is not feasible and wasn't intended at all to allow dynamic modification of these images because there are tons of restrictions to these images to keep the overall design intact. 

Dynamic data is for example:
- `/documents` the documents page
- `/members` the members page
- `/iishf` the IISHF page
- `/news` the news page

Dynamic data however is powered by the content entered into the database through the backend administration system. `/admin/articles` for news, `/admin/documents` for documents, `/admin/national-governing-bodies` for members, `/admin/staff` for IISHF staff and `/admin/committees` for IISHF committees. There is also a backend administration system for the IISHF hall of fame (`/admin/hall-of-fame`) and the tournament management system (`/admin/events/`). The data for both systems is not yet available on the frontend due to missing designs. 

This split makes sense because the static data does not change that often (if it changes at all) while the dynamic data changes constantly. 

A total different story is to add a more fine-grained permission system for the administration backend to allow certain users to only access certain backend systems (news, documents, NGBs, etc). I've opened up a follow-up issue on that one. 

There's also another part that might be handled as dynamic data but is not. That's the photo slider on the homepage. Currently that's static data, but it's easy to add a backend system to manage the images used in the photo slider. I also opened up a separate issue for that.
