### ISSUE TITLE
Hall of Fame

### ISSUE THREAD

**Issue by andrepoddubny** [IISHF/web2019#20]
The Hall of Fame is currently not visible in the front end.

It is possible to change that section towards what I created in Wikipedia, where we have a hall of fame for every tournament that includes the first three countries (medal winners), then provides for a club and/or nations ranking per tournament and eventually also for all tournaments combined. This is not an urgent issue, but will do very nicely on our website. 

https://en.wikipedia.org/wiki/International_Inline-Skater_hockey_Federation#Men_European_Championships

Ideally this part will be immediately filled out by the Technical Director or Technical Assistant at the end of any Title Event. Good if the counting could then occur automatically?

This is not an urgent issue.

**Comment by andrepoddubny** [comment]
I just reviewed the hall of fame. Basically what we need are the following additions:

2nd Place Team
3rd Place Team

Countries for Team 1 - Team 3 and Host.  I suppose from there we can generate later on "medallienspiegel" on a club and country level. If this could be done easily, I will have on of my assistant fill it out today and tomorrow.

**Comment by sgehrig** [comment]
@andrepoddubny This issue is about adding the hall of fame with the data we have to the public website. It's not so much about enhancing the hall of fame concept - which can be a future task. So please open a separate issue with your thoughts about enhancing the hall of fame concept in general.

As discussed the current website more or less replicates the features and the data available on the old site - with some notable enhancements here and there. It's too late now to do significant changes before the MVP release end of February. We should spend the time on getting the real necessities in place quickly for the launch.

Everything else goes into enhancement tasks for later implementation. So please add all your ideas and thoughts for enhancing certain concepts, modules, pages etc. to the Github board.

**Comment by sgehrig** [comment]
A very simple hall of fame page has been added - with lots of room for improvement.
