### ISSUE TITLE
Add Twitter widget to homepage

### ISSUE THREAD

**Issue by sgehrig** [IISHF/web2019#46]
Twitter: https://twitter.com/iishf
Twitter 2: https://twitter.com/iishf_live

We have 2 Twitter accounts. Basically one for the game results and one for general IISHF issues. That means, the one for general IISHF issues basically is being used for just the communication of the Communication Letters. I asked Erik if we do need both. I think that is not very practical...

**Comment by andrepoddubny** [comment]
Dear Stefan, Erik and I have decided that one Twitter account is sufficient, given the way we use them (always at different time). Please embed just the IISHF Twitter account (https://twitter.com/iishf).

The arguments for just one account are following:

- We popularize 2 channels instead of one. Meaning, we make ourselves less significant than we are (obviously we can’t say we have 1,200 subscriptions as we do not know how many persons are subscribed to both accounts).

- Content wise we have with one account 9 weekends full of information (some 22 days per year) and the main account is busy around 25 times per year, but never during the same time as the first account (e.g. during the tournaments). As such there would be no conflict in timing or content if put together.

- We need more efforts to market both channels and include two channels in our Website rather than just one.
